##indexing

In [4]:
import numpy as np
a = np.array([1,2,3,4,5,6])
a[3]
a[1]=5
a

array([1, 5, 3, 4, 5, 6])

##slicing

In [9]:
a[0:4]
b=a[3:]
b
b[0]=40
a

array([ 1,  5,  3, 40,  5,  6])

In [14]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a[2, 2]

np.int64(11)

##Array Attributes


In [19]:
# this covers ndim, shape, size, dtype

a.ndim #number of dimensions
a.shape    #number of elements in each dimension
len(a.shape)==a.ndim
a.size     #total number of elements 
a.dtype    #data type of elements

dtype('int64')

##Create basic array 

In [31]:
## this covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

np.zeros(2)
np.zeros((3,4))  #3 rows and 4 columns of zeros

np.ones(2)
np.ones((3,2))    #3 rows and 2 columns of ones

np.empty(2)
np.empty((2,3))   #2 rows and 3 columns of empty values
#empty create random values and depends on state of memory 

np.arange(6)
np.arange(1,10,3)

np.linspace(1,10,5,dtype=np.int64)  #5 values between 1 and 10 equally spaced


array([ 1,  3,  5,  7, 10])

##Adding, removing, and sorting elements

In [41]:
# covers np.sort(), np.concatenate()

arr = np.array([2,7,5,3,9,6,4])
np.sort(arr)

c = np.array([1,2,3])
d = np.array([4,5,6])
np.concatenate((c,d))

e = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])
np.concatenate((e,d),axis=1)  #row wise concatenation

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

##reshape

In [51]:
f = np.arange(6)
f.reshape((3,2))

g=np.arange(6)
np.reshape(g, shape=(3,2),order = 'c')

array([[0, 1],
       [2, 3],
       [4, 5]])

##Convert 1D array into SD array


In [ ]:
# this covers np.newaxis, np.expand_dims
h = np.array([1,2,3,4,5,6])
h.shape
h2 = h[np.newaxis, :]
h2.shape

h3 = np.array([[1,2,3],[4,5,6]])
h3.shape
h4 = h3[np.newaxis, :]
h4.shape  
"""Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on."""

row_vec = h[np.newaxis, :]  ##convert 1d array to row vector by inserting axis along first dimension
row_vec.shape

col_vec = h[:,np.newaxis]    ## column vector by inserting an axis along second vector
col_vec.shape

##np.expand_dims

i=np.array([1,2,3,4,5,6])
i.shape

j= np.expand_dims(i, axis =1)  ##add axis at index position 1
j.shape

k = np.expand_dims(i, axis =0)  ##add axis at index position 0
k.shape




(1, 6)

##Indexing and Slicing 

In [82]:
l = np.array([1,2,3])
l[0]
l[0:2]
l[1:]
l[-1]
l[-2:]
l[1:-1]


m = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
less_than_five = m[m < 5]
print(less_than_five)

upto_five = m[m>=5]
print(upto_five)

div_2 = m[m%2==0]
print(div_2)

cond_and = m[(m>5) & (m<11)]
print(cond_and)

cond_or = [(m%2==0) | (m>10)]
print(cond_or)

[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[ 6  7  8  9 10]
[array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True,  True,  True]])]


In [85]:
## np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

m1 = np.array([[1,1],[2,2]])
m2 = np.array([[3,3],[4,4]])

np.vstack((m1,m2))  ##stack them vertically

np.hstack((m1,m2))  ##stack them horizontally 
np.hsplit(m1,2)   ##split the array into 2 equal parts horizontally

[array([[1],
        [2]]),
 array([[1],
        [2]])]

##Basics array operation


In [98]:
#this covers addition, sub, div, multi and more

data = np.array([1,2])
ones = np.ones(2,dtype=int)
data + ones
data - ones
data * ones
data / ones
data.sum()

np.int64(3)

##Broadcasting

In [99]:
data1 = np.array([1.0,2.0,3.0])
data * 1.6

array([1.6, 3.2])

##array operations 

In [106]:
## this covers max(), min(), sum(), mean(), prod()

m.max()
m.min()
m.sum()
m.mean()
m.prod()
m.std()

np.float64(3.452052529534663)

In [111]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data[0, 1]
data[0:2, 0]


##random.Generator

rng = np.random.default_rng()
rng.random(4)

array([0.0502216 , 0.90995331, 0.1314086 , 0.16140251])